const config = {
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NWI2OTFmMTI2MDA3YWFmZTk3NDVlZCIsIm5hbWUiOiJBdHJldXMiLCJyb2xlIjpbImFkbWluIl0sImlhdCI6MTcxNzQxODE5MCwiZXhwIjoxNzE3NTA0NTkwfQ.t9pWDYYEPVGJdR4iqJTzkYf9BaqOWhCELfXzn5Iszxc"
}

export default config;